### ISSUE TITLE
CSS Klassen pull-left / pull-right wurden in Bootstrap Beta 2 entfernt

### ISSUE THREAD

**Issue by wiphi** [contao-bootstrap/layout#7]
Die Klassen `pull-left` und `pull-right` wurden in der Beta 2 von Bootstrap entfernt. Stattdessen verwendet man jetzt die Klassen `float-left` und `float-right`. Siehe http://getbootstrap.com/docs/4.0/migration/#utilities

Demzufolge müsste die Datei `src/Resources/config/contao_bootstrap.yml` 
von
```
  replace_css_classes:
      invisible: sr-only
      float_left: pull-left
      float_right: pull-right
```

nach 

```
  replace_css_classes:
      invisible: sr-only
      float_left: float-left
      float_right: float-right
```

geändert werden.
